import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/Header";

import "../../styles/globals.css";
import { gellix } from "@/styles/font";
/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

belongs in className ${geistSans.variable} ${geistMono.variable}
*/

export const metadata: Metadata = {
  title: "Habitat Health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gellix.variable} antialiased p-[--padding] pt-0`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
