import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/Header";

import "../../styles/globals.css";
import { gellix } from "@/styles/font";
import Footer from "@/components/Footer";
import { getSettingsData } from "@/sanity/lib/fetch";
import { Settings } from "@/sanity.types";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

belongs in className ${geistSans.variable} ${geistMono.variable}
*/

export const metadata: Metadata = {
  title: "Habitat Health",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settingsData = await getSettingsData() as Settings;
  const { header } = settingsData;
  return (
    <html lang="en">
      <body
        className={`${gellix.variable} antialiased px-[--padding] py-0`}
      >
        {header && <Header { ...header } />}
        {children}
        <Footer />
      </body>
    </html>
  );
}
